### ISSUE TITLE
Importing Schoolsoft class only outputs { baseURL: 'https://sms.schoolsoft.se' }

### ISSUE THREAD

**Issue by TheFlyingDog42** [CarelessInternet/node-schoolsoft#179]
This is probably me being dumb again, (sorry for wasting your time) but I really would like this to work.
![image](https://user-images.githubusercontent.com/72663115/187983880-b852bf9e-e630-4620-8448-e1c5d0ab6a93.png)
What am I doing wrong?

**Comment by CarelessInternet** [comment]
You have to import the `default` object from `'schoolsoft'`. The SchoolSoft (default) class has a static property called `baseURL` for the base of SchoolSoft's url.

```ts
// CommonJS
const { default: SchoolSoft } = require('schoolsoft');
const school = new SchoolSoft(username, password, school);

// ESM/TypeScript
import SchoolSoft from 'schoolsoft';
const school = new SchoolSoft(username, password, school);

console.log(SchoolSoft.baseURL) // 'https://sms.schoolsoft.se'
```
